# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27018:27017    
    volumes:
      - data:/data/db

volumes:
  data: