# Use root/example as user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: servisbot
    ports:
      - 5432:5432
    restart: unless-stopped